---
# vars file for ldap-perun
prerequisites:
  Debian:
    - slapd
    - ldap-utils
    - python-ldap
  RedHat: []

slapd_service:
  Debian: slapd
  RedHat: []

ssl_conf_dir:
  Debian: '/etc/ldap'
  RedHat: []

slapd_config_admin_dn: 'cn=admin,cn=config'


ldapc_log_file: "{{ perun_log_dir }}/perun-ldapc-out.log"
ldapc_config_file: "{{ perun_config_dir }}/logback-ldapc.xml"

ldapc_utils: "{{ perun_folder }}/perun-utils/ldapc-scripts"

script_files:
  start:
    source: "{{ ldapc_utils }}/start-ldapc.sh"
    destination: "{{ perun_ldapc_folder }}/start-ldapc.sh"
    mode: "0744"
  stop:
    source: "{{ ldapc_utils }}/stop-ldapc.sh"
    destination: "{{ perun_ldapc_folder }}/stop-ldapc.sh"
    mode: "0744"
  initialize:
    source: "{{ ldapc_utils }}/initialize-ldap.sh"
    destination: "{{ perun_ldapc_folder }}/initialize-ldap.sh"
    mode: "0744"
  ldifDiff:
    source: "{{ ldapc_utils }}/ldifdiff.pl"
    destination: "{{ perun_ldapc_folder }}/ldifdiff.pl"
    mode: "0744"
  ldifDiffSort:
    source: "{{ ldapc_utils }}/ldifdiff-sort.pl"
    destination: "{{ perun_ldapc_folder }}/ldifdiff-sort.pl"
    mode: "0744"
  ldifSort:
    source: "{{ ldapc_utils }}/ldifsort.pl"
    destination: "{{ perun_ldapc_folder }}/ldifsort.pl"
    mode: "0744"
  ldapcJar:
    source: "{{ perun_folder }}/perun-ldapc/target/perun-ldapc-3.0.1-SNAPSHOT-production.jar"
    destination: "{{ perun_ldapc_folder }}/perun-ldapc-3.0.1-SNAPSHOT-production.jar"
    mode: "0644"
  ldapcInitializerJar:
    source: "{{ perun_folder }}/perun-ldapc-initializer/target/perun-ldapc-initializer-3.0.1-SNAPSHOT-production.jar"
    destination: "{{ perun_ldapc_folder }}/perun-ldapc-initializer-3.0.1-SNAPSHOT-production.jar"
    mode: "0644"

init_d_script:
  Debian:
    source: "{{ perun_folder }}/perun-utils/init.d-scripts/perun-ldapc.debian"
    destination: "/etc/init.d/perun-ldapc"
    mode: "0755"
