---
# vars file for ldap-perun
prerequisites:
  Debian:
    - slapd
    - ldap-utils
    - python-ldap
  RedHat: []

slapd_service:
  Debian: slapd
  RedHat: []

ssl_conf_dir:
  Debian: '/etc/ldap'
  RedHat: []

temporary_dir_path: "/home/{{ perun_login }}/openldap"

slapd_basedn: '{{ "dc=" + slapd_domain.split(".") | join(",dc=") }}'
slapd_basedn_admin: '{{ "cn=admin," + slapd_basedn }}'
