---
# vars file for ldap-perun
prerequisites:
  Debian:
    - slapd
    - ldap-utils
    - python-ldap
    - libnet-ldap-perl
  RedHat: []

slapd_service:
  Debian: slapd
  RedHat: []

ssl_conf_dir:
  Debian: '/etc/ldap'
  RedHat: []

slapd_config_admin_dn: 'cn=admin,cn=config'


ldapc_log_file: "{{ perun_log_dir }}/perun-ldapc-out.log"
ldapc_config_file: "{{ perun_config_dir }}/logback-ldapc.xml"

ldapc_utils: "{{ perun_folder }}/perun-utils/ldapc-scripts"

script_files:
  ldapcJar:
    source: "{{ perun_folder }}/perun-ldapc/target/perun-ldapc.jar"
    destination: "{{ perun_ldapc_folder }}/perun-ldapc.jar"
    mode: "0644"

init_d_script:
  Debian:
    source: "{{ perun_folder }}/perun-utils/init.d-scripts/perun-ldapc.debian"
    destination: "/etc/init.d/perun-ldapc"
    mode: "0755"

# Template file and destination in remote system for perun-ldapc.properties
perun_ldapc_properties_template: perun_ldapc_properties.j2
perun_ldapc_properties_file: "{{ perun_config_dir }}/perun-ldapc.properties"

# Template file and destination in remote system for logback-ldapc.xml
logback_ldapc_xml_template: logback_ldapc_xml.j2
logback_ldapc_xml_file: "{{ perun_config_dir }}/logback-ldapc.xml"

# Template file and destination in remote system for perun-rpc-lib.properties
perun_rpc_lib_properties_template: perun_rpc_lib_properties.j2
perun_rpc_lib_properties_file: "{{ perun_config_dir }}/perun-rpc-lib.properties"

# Template file and destination in remote system for perun-ldapc-attributes.xml
perun_ldapc_attributes_xml_template: perun_ldapc_attributes_xml.j2
perun_ldapc_attributes_xml_file: "{{ perun_config_dir }}/perun-ldapc-attributes.xml"

# Template file and destination in remote system for perun-ldapc
perun_ldapc_template: perun_ldapc.j2
perun_ldapc_file: "{{ perun_config_dir }}/perun-ldapc"
