---
# vars file for ldap-perun
prerequisites:
  Debian:
    - slapd
  RedHat: []

slapd_service:
  Debian: slapd
  RedHat: []

ssl_conf_dir:
  Debian: '/etc/ldap'
  RedHat: []

temporary_dir_path: "/home/{{ perun_login }}/openldap"
