---
# Sets working environment on Debian to sensible state

- name: fix vim mouse editing
  lineinfile:
    path: "/usr/share/vim/vim81/defaults.vim"
    regexp: "set mouse=a"
    line: '  set mouse=r'
    backrefs: yes
