---
# Sets working environment on Debian to sensible state

- name: Install Czech locale
  locale_gen:
    name: "{{item}}"
    state: present
  with_items:
    - "en_US.UTF-8"
    - "cs_CZ.UTF-8"

- name: Install vim, htop, locate, debian-goodies
  apt:
    name:
      - vim
      - htop
      - locate
      - debian-goodies
    state: latest

- name: create /root/.bashrc if it does not exist
  copy:
    content: ""
    dest: /root/.bashrc
    force: no

- name: fix cmd prompt
  blockinfile:
    dest: /root/.bashrc
    block: |
      # If this is an xterm set the title to user@host:dir
      case "$TERM" in
      xterm*|rxvt*)
         PS1="\[\e]0;\u@$(hostname --fqdn) \w\a\]\u@$(hostname --fqdn):\w# "
         ;;
      *)
         ;;
      esac
      export EDITOR=vi

- name: create /root/.vimrc if it does not exist
  copy:
    content: ""
    dest: /root/.vimrc
    force: no

- name: fix vim
  blockinfile:
    dest: /root/.vimrc
    marker: '" {mark} ANSIBLE MANAGED BLOCK'
    block: |
      " fix mouse
      set mouse=r
      " syntax highlighting
      syntax on
      set background=dark
      " better search
      set incsearch
      " When editing a file, always jump to the last known cursor position.
      " Don't do it when the position is invalid or when inside an event handler
      " (happens when dropping a file on gvim).
      autocmd BufReadPost *
        \ if line("'\"") > 1 && line("'\"") <= line("$") |
        \   exe "normal! g`\"" |
        \ endif
