---
# tasks file for shibboleth-perun
- name: SWITCH repo key
  apt_key:
    id: 15B76742
    url: "http://pkg.switch.ch/switchaai/SWITCHaai-swdistrib.asc"
    state: present

- name: SWITCH repo
  apt_repository:
    repo: "deb http://pkg.switch.ch/switchaai/debian {{ ansible_distribution_release }} main"
    state: present
    filename: 'switch'
    update_cache: yes

- name: backports repo
  apt_repository:
    repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main"
    state: present
    filename: 'backports'
    update_cache: yes

- name: Install Shibboleth
  apt:
    name: shibboleth
    state: latest
    install_recommends: yes

