---

# specific tasks
- include_tasks: "Debian_9.yml"
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "9"

- include_tasks: "Debian_10.yml"
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "10"

# common tasks
- include_tasks: "{{ ansible_distribution }}.yml"

