- name: "Update Perun GUI NG"
  hosts: perun_gui_ng
  remote_user: root
  become: yes
  become_user: perun
  tasks:
    - name: "clone git repository of perun-web-apps"
      git:
        repo: https://github.com/CESNET/perun-web-apps.git
        dest: /home/perun/perun-web-apps
        version: production
        update: yes
        force: yes
      register: git_updated
    - block:
        - name: "backup GUI config"
          copy:
            remote_src: yes
            src: /var/perun-web-apps/admin-gui/assets/config/instanceConfig.json
            dest: /home/perun/instanceConfig.json
          ignore_errors: yes

        - name: "empty the dir /var/perun-web-apps/"
          shell:
            cmd: "rm -rf /var/perun-web-apps/*"
            warn: no

        - name: "deploy perun web apps"
          delegate_to: "{{ inventory_hostname }}"
          synchronize:
            src: "/home/perun/perun-web-apps/dist/apps/"
            dest: /var/perun-web-apps
            rsync_opts:
              - "--exclude=instanceConfig.json"

        - name: "copy GUI configs back to machines"
          copy:
            remote_src: yes
            src: /home/perun/instanceConfig.json
            dest: /var/perun-web-apps/admin-gui/assets/config/instanceConfig.json
      when: git_updated.changed
