---
#  Role for updating LDAP schemas
#  run with:
#  ansible-playbook -i inventories/all update-ldap.yml

- name: Update LDAP schemas on all Perun servers and LDAP replicas
  hosts:
   - ldap_replicas
   - perun_servers
  remote_user: root
  vars:
    perun_version: release3_9
  pre_tasks:
    - name: Require Debian
      assert:
        that:
          - ansible_distribution == "Debian"
          - ansible_distribution_major_version in ["8", "9","10"]
        msg: "Only Debian 8+ is supported"

  roles:
    - update-ldap
