---
- name: "removes user"
  hosts: all
  remote_user: root
  vars:
    login: "vsetepet"
  tasks:
    - name: "delete OS user"
      user:
        name: "{{ login }}"
        remove: yes
        state: absent
    - name: "remove group"
      group:
        name: "{{ login }}"
        state: absent
    - name: "remove from yubikeys"
      lineinfile:
        path:

        regexp: "^{{ login }}"
        state: absent