---
# Main perun orchestration playbook

# Steps to run:
# 1. change the inventories/prod file to contain your host name
# 2. create directory host_vars/<your host name>/ and copy there the files from host_vars/perun.example.com/
# 3. set all values in host_vars/<your host name>/vars.yml
# 4. edit vault by executing the command "ansible-vault -edit host_vars/<your host name>/passwords.yml" and set values in the file
# 5. change vault password by executing the command "ansible-vault rekey host_vars/<your host name>/passwords.yml"
# 6. run the playbook by executing the command "ansible-playbook -i inventories/prod --ask-vault-pass site.yml"

# you can run only specific parts of this playbook using tags, e.g.:
#  ansible-playbook -i inventories/prod --ask-vault-pass site.yml --tags perun,shibboleth,apache

- hosts: perun-servers
  pre_tasks:

  - name: Check that host's variables and passwords are loaded
    assert:
      that:
        - password_perun_admin is defined
        - perun_login is defined
        - perun_hostname is defined
        - perun_email is defined
        - apache_certificate_file is defined
        - apache_certificate_key_file is defined
        - ldap_certificate_file is defined
        - ldap_certificate_key_file is defined
      msg: "Create directory host_vars/{{inventory_hostname}}/, copy there files from host_vars/perun.example.com/ and set all values in them"
    tags: ['always']

  # Debian 7 has only Apache 2.2, which have incompatible config files with Apache 2.4
  - name: Require Debian 8,9
    assert:
      that:
        - ansible_distribution == "Debian"
        - ansible_distribution_major_version in ["8","9"]
      msg: "Only Debian 8,9 are supported"
    tags: ['always']

  # editing the file shibboleth2.xml requires xml task available since Ansible 2.4
  - name:  Ansible 2.4+ required
    assert:
      that:
        - ansible_version is defined
        - ansible_version.full is version_compare('2.4', '>=')
      msg: "Required Ansible version is 2.4+ which contains xml task"
    tags: ['shibboleth']


  roles:
    # NECESSARY ROLES
    # ---------------
    # This role will create user perun and download all packages and GIT repositories you will need in installation process.
    - { role: perun, become: true, tags: perun }
    # This role will copy configuration files of Perun on your server.
    - { role: configuration-perun, become: true, tags: config }
    # This role will install Apache on your server.
    - { role: shibboleth-perun, become: true, tags: shibboleth }
    # This role will install Apache on your server.
    - { role: apache-perun, become: true, tags: apache }
    # This role will install Tomcat on your server.
    - { role: tomcat-perun, become: true, tags: tomcat }
    # This role will deploy Postgre DB on your server and prepares DB tables.
    - { role: postgre-perun, become: true, tags: db}
    # This role will build Perun on your server.
    - { role: build-perun, become: true, tags: build }
    # This role will build engine of Perun on your server.
    - { role: engine-perun, become: true, tags: engine }
    # This role will deploy new web user interface of Perun on your server.
    - { role: wui-perun, become: true, tags: wui}
    # This role will deploy new LDAP server configuration.
    - { role: ldap-perun, become: true, tags: ldap }
    # This role will deploy authentication by hardware Yubikeys.
    - { role: yubikey, become: true, tags: yubikey }
    # This role will deploy unattended upgrades of Debian OS.
    - { role: unattended-upgrades, become: true, tags: unattended-upgrades }
