---
# Main perun orchestration playbook
- hosts: perun-servers
  pre_tasks:
  - name: Pull in site-specific passwords
    include_vars: "{{ item }}"
    with_first_found:
      - files:
        - "passwords-{{ site_name | default('default') }}.yml"
        paths:
        - "."
        - "group_vars"
        - "site_vars"
  roles:
    # NECESSARY ROLES
    # ---------------
    # This role will create user perun and download all packages and GIT repositories you will need in installation process.
    - { role: perun, become: true, tags: perun }
    # This role will copy configuration files of Perun on your server.
    - { role: configuration-perun, become: true, tags: config-perun}
    # This role will install Apache on your server.
    - { role: apache-perun, become: true, tags: apache }
    # This role will install Tomcat on your server.
    - { role: tomcat-perun, become: true, tags: tomcat }
    # This role will deploy Postgre DB on your server and prepares DB tables.
    - { role: postgre-perun, become: true, tags: db}
    # This role will build Perun on your server.
    - { role: build-perun, become: true, tags: build-perun }
    # This role will build engine of Perun on your server.
    - { role: engine-perun, become: true, tags: engine-perun}
    # This role will deploy new web user interface of Perun on your server.
    - { role: wui-perun, become: true, tags: wui-perun}
