---
# Main perun orchestration playbook
- hosts: perun-servers
  strategy: debug
  pre_tasks:
  - name: Pull in site-specific passwords
    include_vars: "{{ item }}"
    with_first_found:
      - files:
        - "passwords-{{ site_name }}.yml"
        paths:
        - "."
        - "group_vars"
        - "site_vars"
  roles:
    # NECESSARY ROLES
    # ---------------
    # This role will create user perun and download all packages and GIT repositories you will need in installation process.
    - { role: perun, become: true, tags: perun }
    # This role will install Apache on your server.
    - { role: apache-perun, become: true, tags: apache }
    # This role will install Tomcat on your server.
    - tomcat-perun
    # This role will deploy Postgre DB on your server and prepares DB tables.
    - postgre-perun
    # This role will copy configuration files of Perun on your server.
    - configuration-perun
    # This role will build Perun on your server.
    - build-perun
    # This role will build engine of Perun on your server.
    - engine-perun
    # This role will deploy LDAP on your server.
    - ldap-perun

    # OPTIONAL ROLES
    # --------------
    #- shibboleth-perun
