---
# Main perun orchestration playbook
- hosts: perun-servers
  roles:
    - perun
    - apache-perun
    - tomcat-perun
    - postgre-perun
    - ldap-perun
  pre_tasks:
    - include_vars: ./group-vars/passwords.yml