galaxy_info:
  author: Jan Zvěřina
  description: Creates Perun user and downloads Perun sources from GIT
  company: CESNET

  license: BSD

  min_ansible_version: 2.2

  platforms:
  - name: Debian
    versions:
    - stretch
    - jessie

  galaxy_tags:
    - web
    - identity
