---
# vars file for engine-perun

init_d_script:
  Debian:
    source: "{{ perun_folder }}/perun-utils/init.d-scripts/perun-engine.debian"
    destination: "/etc/init.d/perun-engine"
    mode: "0755"
