---
# vars file for engine-perun

init_d_script:
  Debian:
    source: "{{ perun_folder }}/perun-utils/init.d-scripts/perun-engine.debian"
    destination: "/etc/init.d/perun-engine"
    mode: "0755"

prerequisites:
  Debian:
  - libswitch-perl
  - liblwp-authen-negotiate-perl
  - libjson-any-perl
  - libtext-asciitable-perl
  - libterm-readkey-perl
  - libwww-perl
  - libcrypt-ssleay-perl
  - libtext-unidecode-perl
  - libdate-calc-perl
  - libnet-ldap-perl
