---
- name: Install unattended-upgrades package
  package:
    name: unattended-upgrades
    state: present

- name: Install sendmail package
  package:
    name: sendmail
    state: present

- name: Install mailutils package
  package:
    name: mailutils
    state: present

- name: Set update sources
  blockinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    insertafter: "Unattended-Upgrade::Origins-Pattern {"
    block: |2
              "origin=Debian,codename=${distro_codename}";
              "origin=Debian,codename=${distro_codename}-updates";

- name: Set email address
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '//Unattended-Upgrade::Mail "root";'
    line:   'Unattended-Upgrade::Mail "root";'
    backrefs: yes

- name: Set email address
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '//Unattended-Upgrade::MailOnlyOnError "true";'
    line:   'Unattended-Upgrade::MailOnlyOnError "true";'
    backrefs: yes

- name: Set aliases
  blockinfile:
    path: /etc/aliases
    block: |2
      root: {{root_email_address}}
