---
- name: Check that variables are loaded
  assert:
    that:
      - root_email_address is defined
    msg: "Create directory host_vars/{{inventory_hostname}}/, copy there file host_vars/perun.example.com/vars.yml and set values in it"

- include_tasks: "{{ ansible_distribution }}.yml"

