---

postgres_version:
  Debian_9: 11
  Debian_buster/sid: 11

psql_version: "{{postgres_version[ansible_distribution+'_'+ansible_distribution_major_version]}}"

postgre_packages:
  Debian_9:
    - postgresql-11
  Debian_buster/sid:
    - postgresql-11


python_psycopg2_package:
  Debian: python-psycopg2

init_user_first_name: Master
init_user_last_name: Perun

postgres_conf_file_path: "{{ perun_folder }}/perun-db/postgres.sql"
