---
# Tasks file for perun-web-apps

- name: Clone git repository of perun-web-apps to remote server
  become: yes
  become_user: "{{ perun_login }}"
  git:
    repo: https://github.com/CESNET/perun-web-apps.git
    dest: "{{ perun_web_apps_folder }}"
    version: production
    update: yes
  register: git_updated

- name: "Build perun web apps. WARNING: THIS CAN TAKE SEVERAL MINUTES!"
  become: yes
  become_user: "{{ perun_login }}"
  shell: "mvn clean install -DskipTests"
  args:
    chdir: "{{ perun_web_apps_folder }}"
  async: 1200
  poll: 5
  when: git_updated.changed

- name: "Delete /var/perun-web-apps directory if exists"
  file:
    path: "/var/perun-web-apps"
    state: absent

- name: "Create /var/perun-web-apps directory"
  file:
    path: "/var/perun-web-apps"
    state: directory
    owner: "{{ perun_login }}"
    group: "{{ perun_group }}"

- name: Deploy perun web apps
  become: yes
  become_user: "{{ perun_login }}"
  command: rsync --delete --exclude='instanceConfig.json' {{ perun_web_apps_folder }}/dist/apps/ /var/perun-web-apps
  args:
    creates: "/var/perun-web-apps/admin-gui"
