---

- name: Check that variables are loaded
  assert:
    that:
      - perun_login is defined
      - perun_group is defined
      - perun_folder is defined

- name: prerequisites installed
  apt:
    name:
     - python-ldap
     - git
     - aptitude
     - ldap-utils

#- name: Set indexes (olcDbIndex attribute)
#  ldap_attr:
#    dn: olcDatabase={1}mdb,cn=config
#    name: olcDbIndex
#    values: "{{ item }}"
#    state: present
#  with_items:
#    - cn,uid eq
#    - uidNumber,gidNumber eq
#    - member,memberUid eq
#    - perunVoId eq
#    - eduPersonPrincipalNames eq
#    - entryCSN,entryUUID eq
#    - login eq
#    - memberOfPerunVo eq
#    - userCertificateSubject eq
#    - entityID eq
#    - assignedToResourceId eq
#  notify: Restart LDAP

- name: "{{ perun_group }} group"
  group:
    name: "{{ perun_group }}"
    system: yes

- name: "{{ perun_login }} user"
  user:
    name: "{{ perun_login }}"
    group: "{{ perun_group }}"
    comment: "{{ perun_name }}"
    shell: /bin/bash
    system: yes

- name: Clone git repository of perun sources to remote server
  become: yes
  become_user: "{{perun_login}}"
  git:
    repo: https://github.com/CESNET/perun.git
    dest: "{{perun_folder}}"
    version: master
    update: yes

- stat:
    path: "{{perun_folder}}/perun-utils/ldapc-scripts/schemas/perun-schema.ldif"
  register: schema_ldif

- assert:
    that:
      - schema_ldif.stat.exists
    msg: "file {{perun_folder}}/perun-utils/ldapc-scripts/schemas/perun-schema.ldif does not exist"

- name: Set up perun schema attributes
  command: "/usr/bin/ldapmodify -Q -H ldapi:/// -Y EXTERNAL -f  {{perun_folder}}/perun-utils/ldapc-scripts/schemas/perun-schema.ldif"
