---

- name: python-ldap
  apt:
    name: python-ldap

- name: Set indexes (olcDbIndex attribute)
  ldap_attr:
    dn: olcDatabase={1}mdb,cn=config
    name: olcDbIndex
    values: "{{ item }}"
    state: present
  with_items:
    - cn,uid eq
    - uidNumber,gidNumber eq
    - member,memberUid eq
    - perunVoId eq
    - eduPersonPrincipalNames eq
    - entryCSN,entryUUID eq
    - login eq
    - memberOfPerunVo eq
    - userCertificateSubject eq
    - entityID eq
    - assignedToResourceId eq
  notify: Restart LDAP
