---
# tool for setting firewall rules
- name: Install iptables package
  package:
    name: iptables
    state: present

# tool for saving firewall rules to /etc/iptables/rules.v4 and /etc/iptables/rules.v6 to survive reboot
- name: Install iptables-persistent package
  package:
    name: iptables-persistent
    state: present
  register: ipper

# blocks IP addresses after multiple unsuccessful authentication attempts
- name: Install fail2ban package
  package:
    name: fail2ban
    state: present

# set up FW rules if package iptables-persistent was just installed

- name: Stop fail2ban
  service:
    name: fail2ban
    state: stopped
  when: ipper.changed

- name: Set up firewall rules
  template:
    backup: true
    force: "{{ overwrite_firewall_rules }}"
    src: rules.j2
    dest: "{{ item }}"
  with_items:
    - /etc/iptables/rules.v4
    - /etc/iptables/rules.v6
  when: ipper.changed

- name: Activate IPv4 firewall rules
  command: /sbin/iptables-restore /etc/iptables/rules.v4
  when: ipper.changed

- name: Activate IPv6 firewall rules
  command: /sbin/ip6tables-restore /etc/iptables/rules.v6
  when: ipper.changed

- name: Start fail2ban
  service:
    name: fail2ban
    state: started
  when: ipper.changed

# lock root password
- name: Lock root password
  user:
    name: root
    password: "*"
