---
- name: SWITCH repo key
  apt_key:
    id: 15B76742
    url: "http://pkg.switch.ch/switchaai/SWITCHaai-swdistrib.asc"
    state: present

#- name: PHP repo key
#  apt_key:
#    id: B188E2B695BD4743
#    url: "https://packages.sury.org/php/apt.gpg"
#    state: present

- name: SWITCH repo
  apt_repository:
    repo: "deb http://pkg.switch.ch/switchaai/debian {{ ansible_distribution_release }} main"
    state: present
    filename: 'switch'
    update_cache: yes

- name: backports repo
  apt_repository:
    repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main"
    state: present
    filename: 'backports'
    update_cache: yes

- name: Install from backports
  apt:
    name:
      - init-system-helpers
      - libxerces-c3.2
    default_release: "{{ ansible_distribution_release }}-backports"
    state: latest
    update_cache: yes

- name: dist-upgrade
  apt:
    upgrade: dist

- name: autoremove
  apt:
    autoremove: yes

- name: remove shib2 transitional packages
  apt:
    name:
      - libapache2-mod-shib2
      - shibboleth-sp2-common
      - shibboleth-sp2-utils
    state: absent
    purge: yes

- name: ensure shibboleth installed
  apt:
    name: shibboleth
    state: latest
    install_recommends: yes

- name: change namespace in shibboleth2.xml
  replace:
    backup: yes
    path: /etc/shibboleth/shibboleth2.xml
    regexp: 'urn:mace:shibboleth:2.0:native:sp:config'
    replace: 'urn:mace:shibboleth:3.0:native:sp:config'
  register: namespc

- name: change uri= to url= in shibboleth2.xml
  replace:
    backup: yes
    path: /etc/shibboleth/shibboleth2.xml
    regexp: ' uri="'
    replace: ' url="'
  register: uriurl

- name: stop shibd
  service:
    state: stopped
    name: shibd
  when: namespc.changed or uriurl.changed

- name: remove warn log
  file:
    path: /var/log/shibboleth/shibd_warn.log
    state: absent
  when: namespc.changed or uriurl.changed

- name: start shibd
  service:
    state: started
    name: shibd
  when: namespc.changed or uriurl.changed
