---
# Debian installation of packages
- name: Ensure prerequisites
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{prerequisites[ansible_os_family]}}"

- name: Copy ojdbc7 file to remote server
  copy:
    src: "{{ ojdbc7_file_path }}"
    dest: "/home/{{ perun_login }}/ojdbc7.jar"
    owner: "{{ perun_login }}"
    group: "{{ perun_group }}"
    mode: 0644

- name: Copy orai18n file to remote server
  copy:
    src: "{{ orai18n_file_path }}"
    dest: "/home/{{ perun_login }}/orai18n.jar"
    owner: "{{ perun_login }}"
    group: "{{ perun_group }}"
    mode: 0644

- name: Install ojdbc7
  become: yes
  become_user: "{{ perun_login }}"
  command: mvn install:install-file -Dfile=ojdbc7.jar -DgroupId=com.oracle -DartifactId=ojdbc7 -Dversion=12.1.0.2.0 -Dpackaging=jar
  args:
    chdir: "/home/{{ perun_login }}"

- name: Install orai18n
  become: yes
  become_user: "{{ perun_login }}"
  command: mvn install:install-file -Dfile=orai18n.jar -DgroupId=com.oracle -DartifactId=orai18n -Dversion=12.1.0.2.0 -Dpackaging=jar
  args:
    chdir: "/home/{{ perun_login }}"

- name: "Build all perun components. WARNING: THIS CAN TAKE SEVERAL MINUTES!"
  become: yes
  become_user: "{{ perun_login }}"
  shell: "mvn -T {{ maven_parallel_build_threads | default(1) }} clean install -DskipTests -Dproduction > out.log"
  args:
    chdir: "{{ perun_folder }}"
  register: perun_build
  async: 600
  poll: 5

- name: debug  build output
  debug:
    var: perun_build.stderr

- name: Copy perun-rpc.war file into tomcat webapps folder
  become: yes
  become_user: "{{ perun_login }}"
  command: cp perun-rpc.war "/home/{{ perun_login }}/tomcat/webapps/perun-rpc.war"
  args:
    chdir: "{{ perun_folder }}/perun-rpc/target/"

- name: Delete /var/www/perun-web-gui-3.0.1-SNAPSHOT-production if exists
  file:
    path: "/var/www/perun-web-gui-3.0.1-SNAPSHOT-production"
    state: absent

- name: Deploy GUI
  command: cp -r ./perun-web-gui-3.0.1-SNAPSHOT-production /var/www/
  args:
    chdir: "{{ perun_folder }}/perun-web-gui/target/"

- name: Start Tomcat if its not running
  service:
    state: started
    state: reloaded
    name: tomcat7
