---
- name: Install prerequisites
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{prerequisites[ansible_distribution]}}"

- name: "Build whole Perun Maven project (rpc, web-gui, engine, ldapc, ...) WARNING: THIS CAN TAKE SEVERAL MINUTES!"
  become: yes
  become_user: "{{ perun_login }}"
  shell: "mvn --batch-mode install -DskipTests -Doracle={{install_oracle}}  > out.log"
  args:
    chdir: "{{ perun_folder }}"
    creates: "{{perun_folder}}/perun-rpc/target/perun-rpc.war"
  register: perun_build
  async: 600
  poll: 5

- name: Debug build output
  debug:
    var: perun_build.stderr

