---
# Tasks file for wui-perun

- name: Clone git repository of Perun's WUI to remote server
  become: yes
  become_user: "{{ perun_login }}"
  git:
    repo: https://github.com/CESNET/perun-wui.git
    dest: "{{ perun_wui_folder }}"
    version: master
    update: yes
  register: git_updated

- name: "Build Perun's Web User Interface. WARNING: THIS CAN TAKE SEVERAL MINUTES!"
  become: yes
  become_user: "{{ perun_login }}"
  shell: "mvn clean install -DskipTests"
  args:
    chdir: "{{ perun_wui_folder }}"
  async: 1200
  poll: 5
  when: git_updated.changed

- name: "Delete /var/www/perun-wui directory if exists"
  file:
    path: "/var/www/perun-wui"
    state: absent

- name: "Create /var/www/perun-wui directory"
  file:
    path: "/var/www/perun-wui"
    state: directory
    owner: "{{ perun_login }}"
    group: "{{ perun_group }}"

- name: Deploy WUI - Admin
  become: yes
  become_user: "{{ perun_login }}"
  command: rsync --exclude "WEB-INF" --exclude "META-INF" -avz {{ perun_wui_admin }} /var/www/perun-wui/
  args:
    creates: "/var/www/perun-wui/PerunAdmin"

- name: Deploy WUI - Profile
  become: yes
  become_user: "{{ perun_login }}"
  command: rsync --exclude "WEB-INF" --exclude "META-INF" -avz {{ perun_wui_profile }} /var/www/perun-wui/
  args:
    creates: "/var/www/perun-wui/PerunProfile"

- name: Deploy WUI - Password Reset
  become: yes
  become_user: "{{ perun_login }}"
  command: rsync --exclude "WEB-INF" --exclude "META-INF" -avz {{ perun_wui_pwdreset }} /var/www/perun-wui/
  args:
    creates: "/var/www/perun-wui/PerunPwdReset"

- name: Deploy WUI - Registrar
  become: yes
  become_user: "{{ perun_login }}"
  command: rsync --exclude "WEB-INF" --exclude "META-INF" -avz {{ perun_wui_registrar }} /var/www/perun-wui/
  args:
    creates: "/var/www/perun-wui/PerunRegistrar"

- name: Deploy WUI - Set Affiliation
  become: yes
  become_user: "{{ perun_login }}"
  command: rsync --exclude "WEB-INF" --exclude "META-INF" -avz {{ perun_wui_setaffiliation }} /var/www/perun-wui/
  args:
    creates: "/var/www/perun-wui/PerunSetAffiliation"

- name: Deploy WUI - Identity Consolidator
  become: yes
  become_user: "{{ perun_login }}"
  command: rsync --exclude "WEB-INF" --exclude "META-INF" -avz {{ perun_wui_consolidator }} /var/www/perun-wui/
  args:
    creates: "/var/www/perun-wui/PerunConsolidator"

- name: Deploy WUI - Cabinet
  become: yes
  become_user: "{{ perun_login }}"
  command: rsync --exclude "WEB-INF" --exclude "META-INF" -avz {{ perun_wui_cabinet }} /var/www/perun-wui/
  args:
    creates: "/var/www/perun-wui/PerunCabinet"
