---
# Tasks file for configuration-perun

- name: Include variable files
  include_vars: "{{ item }}"
  with_fileglob:
    - ../vars/*

- name: Make "{{ perun_var_log_repo }}" directory
  file:
    path: "{{ perun_var_log_repo }}"
    state: directory
    mode: 0755
    owner: "{{ perun_login }}"
    group: "{{ perun_group }}"

- name: Make "{{ perun_repo }}" directory
  file:
    path: "{{ perun_repo }}"
    state: directory
    mode: 0755
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"

- name: Make "{{ perun_repo_ssl }}" directory
  file:
    path: "{{ perun_repo_ssl }}"
    state: directory
    mode: 0755

- name: Create file "{{ logback_dir }}"
  template:
    src: "{{ logback_template }}"
    dest: "{{ logback_dir }}"
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"
    mode: 0644

- name: Create file "{{ logback_engine_dir }}"
  template:
    src: "{{ logback_engine_template }}"
    dest: "{{ logback_engine_dir }}"
    owner: "{{ perun_login }}"
    group: "{{ perun_group }}"
    mode: 0644

- name: Create file "{{ jdbc_dir }}"
  template:
    src: "{{ jdbc_template }}"
    dest: "{{ jdbc_dir }}"
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"
    mode: 0644

- name: Create file "{{ perun_notification_dir }}"
  template:
    src: "{{ perun_notification_template }}"
    dest: "{{ perun_notification_dir }}"
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"
    mode: 0644

- name: Create file "{{ perun_cabinet_dir }}"
  template:
    src: "{{ perun_cabinet_template }}"
    dest: "{{ perun_cabinet_dir }}"
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"
    mode: 0644

- name: Create file "{{ perun_dispatcher_dir }}"
  template:
    src: "{{ perun_dispatcher_template }}"
    dest: "{{ perun_dispatcher_dir }}"
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"
    mode: 0644

- name: Create file "{{ perun_engine_dir }}"
  template:
    src: "{{ perun_engine_template }}"
    dest: "{{ perun_engine_dir }}"
    mode: 0644

- name: Create file "{{ perun_engine_properties_dir }}"
  template:
    src: "{{ perun_engine_properties_template }}"
    dest: "{{ perun_engine_properties_dir }}"
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"
    mode: 0644

- name: Create file "{{ perun_registrar_lib_dir }}"
  template:
    src: "{{ perun_registrar_lib_template }}"
    dest: "{{ perun_registrar_lib_dir }}"
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"
    mode: 0644

- name: Create file "{{ perun_rpc_lib_dir }}"
  template:
    src: "{{ perun_rpc_lib_template }}"
    dest: "{{ perun_rpc_lib_dir }}"
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"
    mode: 0644

- name: Create file "{{ perun_web_gui_dir }}"
  template:
    src: "{{ perun_web_gui_template }}"
    dest: "{{ perun_web_gui_dir }}"
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"
    mode: 0644

- name: Create file "{{ perun_ext_sources_dir }}"
  template:
    src: "{{ perun_ext_sources_template }}"
    dest: "{{ perun_ext_sources_dir }}"
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"
    mode: 0644

- name: Create file "{{ perun_conf_dir }}"
  template:
    src: "{{ perun_conf_template }}"
    dest: "{{ perun_conf_dir }}"
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"
    mode: 0644
