---
# Tasks file for configuration-perun


- name: Make "{{ perun_config_dir }}" directory
  file:
    path: "{{ perun_config_dir }}"
    state: directory
    mode: 0755
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"

- name: Create file "{{ logback_xml_file }}"
  template:
    src: "{{ logback_xml_template }}"
    dest: "{{ logback_xml_file }}"
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"
    mode: 0640
    force: no

- name: Create file "{{ logback_engine_xml_file }}"
  template:
    src: "{{ logback_engine_xml_template }}"
    dest: "{{ logback_engine_xml_file }}"
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"
    mode: 0640
    force: no

- name: Create file "{{ jdbc_properties_file }}"
  template:
    src: "{{ jdbc_properties_template }}"
    dest: "{{ jdbc_properties_file }}"
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"
    mode: 0640
    force: no

- name: Create file "{{ perun_notification_properties_file }}"
  template:
    src: "{{ perun_notification_properties_template }}"
    dest: "{{ perun_notification_properties_file }}"
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"
    mode: 0640
    force: no

- name: Create file "{{ perun_cabinet_properties_file }}"
  template:
    src: "{{ perun_cabinet_properties_template }}"
    dest: "{{ perun_cabinet_properties_file }}"
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"
    mode: 0640
    force: no

- name: Create file "{{ perun_dispatcher_properties_file }}"
  template:
    src: "{{ perun_dispatcher_properties_template }}"
    dest: "{{ perun_dispatcher_properties_file }}"
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"
    mode: 0640
    force: no

- name: Create file "{{ perun_engine_file }}"
  template:
    src: "{{ perun_engine_template }}"
    dest: "{{ perun_engine_file }}"
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"
    mode: 0640
    force: no

- name: Create file "{{ perun_engine_properties_file }}"
  template:
    src: "{{ perun_engine_properties_template }}"
    dest: "{{ perun_engine_properties_file }}"
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"
    mode: 0640
    force: no

- name: Create file "{{ perun_registrar_lib_properties_file }}"
  template:
    src: "{{ perun_registrar_lib_properties_template }}"
    dest: "{{ perun_registrar_lib_properties_file }}"
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"
    mode: 0640
    force: no

- name: Create file "{{ perun_web_gui_properties_file }}"
  template:
    src: "{{ perun_web_gui_properties_template }}"
    dest: "{{ perun_web_gui_properties_file }}"
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"
    mode: 0640
    force: no

- name: Create file "{{ perun_ext_sources_xml_file }}"
  template:
    src: "{{ perun_ext_sources_xml_template }}"
    dest: "{{ perun_ext_sources_xml_file }}"
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"
    mode: 0640
    force: no

- name: Create file "{{ perun_properties_file }}"
  template:
    src: "{{ perun_properties_template }}"
    dest: "{{ perun_properties_file }}"
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"
    mode: 0640
    force: no

- name: Create file "{{ perun_roles_yml_file }}"
  template:
    src: "{{ perun_roles_yml_template }}"
    dest: "{{ perun_roles_yml_file }}"
    owner: "{{ config_files_owner }}"
    group: "{{ perun_group }}"
    mode: 0640
    force: no
