---
# vars file for perun
perun_login: perun
perun_group: perun
perun_name: Mr. Perun
perun_password: hahanoway
perun_admin: 'admin@perun-test-domain.com'
perun_email: 'perun@perun-test-domain.com'

# Virtual host config file
perun_apache_conf:
  Debian: perun.conf.j2
  RedHat: perun.conf.j2
perun_apache_dir:
  Debian: /etc/apache2/sites-enabled/
  RedHat: /etc/httpd/conf.d/
