---
# fixes security bug in Shibboleth SP
- name: Update packages for shibd
  apt:
    name:
      - libsaml10
      - opensaml-schemas
    state: latest
    update_cache: yes
  register: shibupdate

- name: restart shibd
  service:
    state: restarted
    name: shibd
  when: shibupdate.changed
