---
# Variables for Registrar
# NOTE: SECRET KEY for authentication messages stored in group_vars/passwords.yml file

# Backup email adresses
backup_from: ''
backup_to: ''

# URL paths behind Shibboleth (since links with anchors needs to be escaped for users)
fed_authz: 'fed'
