---
- name: Create temporary directory for temporary LDAP files
  file:
    state: directory
    path: "{{ temporary_dir_path }}"
    owner: "{{ perun_login }}"
    group: "{{ perun_group }}"
    mode: 0755

- name: Copy perun.ldif to remote server
  template:
    src: "perun_ldif.j2"
    dest: "{{ temporary_dir_path }}/perun.ldif"
    owner: openldap
    group: openldap
    mode: 0640

- name: Copy inetuser.ldif to remote server
  template:
    src: "inetuser_ldif.j2"
    dest: "{{ temporary_dir_path }}/inetuser.ldif"
    owner: openldap
    group: openldap
    mode: 0640

- name: Copy init-perun.ldif to remote server
  template:
    src: "init_perun_ldif.j2"
    dest: "{{ temporary_dir_path }}/init-perun.ldif"
    owner: openldap
    group: openldap
    mode: 0640

- name: Execute files with ldapadd
  command: ldapadd -Y EXTERNAL -H ldapi:/// -f {{ item }}
  args:
    chdir: "{{ temporary_dir_path }}"
  with_items:
    - perun.ldif
    - inetuser.ldif
  ignore_errors: true

- name: Generate the root password for ldap
  shell: slappasswd -s {{ password_ldap_root }}
  register: root_password

# Dependency on root_password variable registered from slappasswd command
- name: Copy settings.ldif to remote server
  template:
    src: "settings_ldif.j2"
    dest: "{{ temporary_dir_path }}/settings.ldif"
    owner: openldap
    group: openldap
    mode: 0640

- name: Execute file init-perun.ldif
  command: ldapadd -Y EXTERNAL -H ldapi:/// -f {{ item }}
  args:
    chdir: "{{ temporary_dir_path }}"
  with_items:
    - settings.ldif
    #- init-perun.ldif
  ignore_errors: true

- name: Delete temporary directory with temporary files
  file:
    state: absent
    path: "{{ temporary_dir_path }}"
