---
# Task file for installation of LDAPc in Debian distribution

- name: Create perun-ldapc folder in perun's home repository
  file:
    path: "{{ perun_ldapc_folder }}"
    state: directory
    owner: "{{ perun_login }}"
    group: "{{ perun_group }}"
    mode: 0755

- name: Copy scripts for ldapc
  copy:
    src: "{{ item.value.source }}"
    dest: "{{ item.value.destination }}"
    owner: "{{ perun_login }}"
    group: "{{ perun_group }}"
    mode: "{{ item.value.mode }}"
    remote_src: yes
  with_dict: "{{ script_files }}"

- name: Copy init.d script for perun-ldapc
  copy:
    src: "{{ init_d_script[ansible_os_family].source }}"
    dest: "{{ init_d_script[ansible_os_family].destination }}"
    owner: root
    group: root
    mode: "{{ init_d_script[ansible_os_family].mode }}"
    remote_src: yes

- name: Create truststore in perun-ldapc folder if you use snake-oil certificate
  java_cert:
    cert_path: "{{ apache_certificate_file }}"
    cert_alias: default
    keystore_path: "{{ perun_ldapc_folder }}/truststore"
    keystore_pass: "{{ password_ldap_snakeoil_truststore }}"
    keystore_create: yes
    state: present
  when: apache_certificate_file == "/etc/perun/ssl/ssl-cert-snakeoil.pem"

- name: Change JAVA_OPTIONS in initialize script to use truststore with snake-oil certificate
  lineinfile:
    path: "{{ script_files.initialize.destination }}"
    regexp: '^JAVA_OPTIONS='
    line: 'JAVA_OPTIONS=" -Dspring.profiles.default=production -Djavax.net.ssl.trustStore={{ perun_ldapc_folder }}/truststore -Djavax.net.ssl.trustStorePassword={{ password_ldap_snakeoil_truststore }} -Djavax.net.ssl.trustStoreType=JKS"'
  when: apache_certificate_file == "/etc/perun/ssl/ssl-cert-snakeoil.pem"

- name: Run initialize script
  ignore_errors: True
  command: "{{ script_files.initialize.destination }}"
  become: yes
  become_user: "{{ perun_login }}"

- name: Start LDAPc
  command: "{{ script_files.start.destination }}"
  become: yes
  become_user: "{{ perun_login }}"
