---
# tasks file for ldap-perun
- include: "{{ ansible_os_family }}.yml"

# SSL configuration ldif
- name: SSL configuration ldif in /etc/ldap/ssl.ldif
  template:
    src: "{{ ssl_conf[ansible_os_family] }}"
    dest: "{{ ssl_conf_dir[ansible_os_family] }}/ssl.ldif"
    owner: "{{ perun_login }}"
    group: "{{ perun_group }}"
    mode: 0644

#- name: Execute ssl.ldif as root
#  become: yes
#  become_user: root
#  command: ldapmodify -Y EXTERNAL -H ldapi:/// -f "{{ ssl_conf_dir[ansible_os_family] }}/ssl.ldif"

- name: Enable secure port in /etc/default/slapd
  lineinfile: 
   dest: /etc/default/slapd 
   regexp: ^SLAPD_SERVICES= 
   line: SLAPD_SERVICES="ldaps:/// ldapi:///"

- name: Restart LDAP
  service: 
    name: "{{ slapd_package[ansible_os_family ]}}" 
    state: restarted 
    enabled: yes