---

- name: "Install ssl-cert package"
  apt:
    name: ssl-cert
    state: latest

# ssl-cert group is created by ssl-cert package, which is dependency of apache2
# ssl-cert group is used by packages like postgres and openldap which need access to private keys
# perun user needs access to site key for authentication when uploading to URLs
- name: Add user {{ perun_login }} to group ssl-cert
  user:
    name: "{{ perun_login }}"
    groups: ssl-cert
    append: yes

- name: Make "{{ perun_ssl_dir }}" directory
  file:
    path: "{{ perun_ssl_dir }}"
    state: directory
    mode: 0755

# Fake Snake Oil if ssl_certificate_file variable is not filled
- name: Make fake Snake Oil certificate for testing purposes
  command: make-ssl-cert generate-default-snakeoil
  args:
    creates: /etc/perun/ssl/ssl-cert-snakeoil.pem
  when: apache_certificate_file == "/etc/perun/ssl/ssl-cert-snakeoil.pem"

- name: Copy Snake Oil certificate to /etc/perun/ssl folder
  command: cp /etc/ssl/certs/ssl-cert-snakeoil.pem /etc/ssl/private/ssl-cert-snakeoil.key /etc/perun/ssl/
  args:
    creates: /etc/perun/ssl/ssl-cert-snakeoil.pem
  when: apache_certificate_file == "/etc/perun/ssl/ssl-cert-snakeoil.pem"

- name: Check rights on certificate
  file:
    path: "{{ apache_certificate_file }}"
    follow: yes
    owner: root
    group: root
    mode: 0644

- name: Check rights on certificate key
  file:
    path: "{{ apache_certificate_key_file }}"
    follow: yes
    owner: root
    group: ssl-cert
    mode: 0640
