# tasks file for apache-perun
- name: Install Apache
  package:
    name: "{{ apache_package[ansible_os_family ]}}"
    state: present

- name: Enable SSL
  apache2_module:
    name: ssl
    state: present

- name: Enable proxy
  apache2_module:
    name: proxy
    state: present

- name: Enable proxy_ajp
  apache2_module:
    name: proxy_ajp
    state: present

- name: Enable rewrite
  apache2_module:
    name: rewrite
    state: present

- name: Copy perun.conf file to /etc/apache2/sites-enabled/perun.conf
  template:
    src: "{{ perun_conf_file }}"
    dest: /etc/apache2/sites-enabled/perun.conf
    owner: "{{ perun_login }}"
    group: "{{ perun_group }}"
    mode: 0644
