---
- name: Require Debian 9
  assert:
    that:
      - ansible_distribution == "Debian"
      - ansible_distribution_major_version == "9"
    msg: "Debian 9 specific tasks"

- name: fix vim mouse editing
  lineinfile:
    path: "/usr/share/vim/vim80/defaults.vim"
    regexp: "set mouse=a"
    state: absent

- name: Use cronolog for error log rotation
  lineinfile:
    path: "/etc/apache2/apache2.conf"
    regexp: 'ErrorLog \${APACHE_LOG_DIR}/error.log'
    line: 'ErrorLog "|/usr/bin/cronolog /var/log/apache2/%Y/%m/%d/error.log"'
    backrefs: yes
  notify:
      - "restart webserver"

- name: Use cronolog for access log rotation
  lineinfile:
    path: "/etc/apache2/conf-enabled/other-vhosts-access-log.conf"
    regexp: 'CustomLog \${APACHE_LOG_DIR}/other_vhosts_access.log vhost_combined'
    line: 'CustomLog "|/usr/bin/cronolog /var/log/apache2/%Y/%m/%d/access.log" vhost_combined'
    backrefs: yes
  notify:
      - "restart webserver"

- name: Set ServerTokens level to Production
  lineinfile:
    path: "/etc/apache2/conf-enabled/security.conf"
    regexp: 'ServerTokens OS'
    line: 'ServerTokens Prod'
    backrefs: yes
  notify:
      - "restart webserver"

- name: Comment out default SSLCipherSuite
  lineinfile:
    path: "/etc/apache2/mods-enabled/ssl.conf"
    regexp: 'SSLCipherSuite HIGH:!aNULL'
    line: ' #SSLCipherSuite HIGH:!aNULL'
  notify:
      - "restart webserver"

- name: Comment out default SSLProtocol
  lineinfile:
    path: "/etc/apache2/mods-enabled/ssl.conf"
    regexp: 'SSLProtocol all -SSLv3'
    line: ' #SSLProtocol all -SSLv3'
  notify:
      - "restart webserver"

- name: Set up TLS correctly
  blockinfile:
    dest: "/etc/apache2/mods-enabled/ssl.conf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertbefore: '</IfModule>'
    block: |
      # see https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=apache-2.4.25&openssl=1.0.2l&hsts=yes&profile=modern
      SSLProtocol             all -SSLv3 -TLSv1 -TLSv1.1
      SSLCipherSuite          ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
      SSLHonorCipherOrder     on
      SSLCompression          off
      SSLSessionTickets       off

      # OCSP Stapling, only in httpd 2.3.3 and later
      SSLUseStapling          on
      SSLStaplingResponderTimeout 5
      SSLStaplingReturnResponderErrors off
      SSLStaplingCache        shmcb:/var/run/ocsp(128000)

- name: Create HTTP2 module config
  copy:
    dest: "/etc/apache2/mods-available/http2.conf"
    content: |
      Protocols h2 http/1.1

- name: Enable HTTP2 module
  apache2_module:
    name: http2
    state: present
  notify:
    - "restart webserver"
