# Tasks file for apache-perun

# Install ssl-cert for making certificate
- name: Install ssl-cert package
  package:
    name: "{{ ssl_cert_package[ansible_os_family] }}"
    state: present
  when: apache_certificate_file == "/etc/perun/ssl/ssl-cert-snakeoil.pem"

# Fake Snake Oil if ssl_certificate_file variable is not filled
- name: Make fake Snake Oil certificate for testing purposes
  command: make-ssl-cert generate-default-snakeoil
  args:
    creates: /etc/perun/ssl/ssl-cert-snakeoil.pem
  when: apache_certificate_file == "/etc/perun/ssl/ssl-cert-snakeoil.pem"

- name: Copy Snake Oil certificate to /etc/perun/ssl folder
  command: cp /etc/ssl/certs/ssl-cert-snakeoil.pem /etc/ssl/private/ssl-cert-snakeoil.key /etc/perun/ssl/
  args:
    creates: /etc/perun/ssl/ssl-cert-snakeoil.pem
  when: apache_certificate_file == "/etc/perun/ssl/ssl-cert-snakeoil.pem"

- name: Check rights on certificate
  file:
    path: "{{ apache_certificate_file }}"
    owner: root
    group: root
    mode: 0644

- name: Check rights on certificate key
  file:
    path: "{{ apache_certificate_key_file }}"
    owner: root
    group: ssl-cert
    mode: 0640

- name: Install Apache
  package:
    name: "{{ apache_package[ansible_os_family] }}"
    state: present

- name: Enable modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items: "{{ apache_modules[ansible_os_family] }}"
  notify:
    - "restart webserver"

- name: Remove default Apache site
  file:
    path: "/etc/apache2/sites-enabled/{{ item }}"
    state: absent
  with_items:
    - 000-default.conf
    - default-ssl.conf
  notify:
    - "restart webserver"

- name: Create Apache configuration files in /etc/apache2/sites-available/
  template:
    src: "{{ item }}.j2"
    dest: "/etc/apache2/sites-available/{{ item }}"
    force: no
    mode: 0644
  with_items:
    - perun.conf
    - perun-ssl.conf

- name: Enable Perun sites in Apache
  command:  a2ensite "{{ item }}"
  args:
    creates: "/etc/apache2/sites-enabled/{{ item }}"
  with_items:
    - perun.conf
    - perun-ssl.conf
  notify:
    - "restart webserver"

- name: Create directory for maintenance files
  file:
    path: /var/www/maintenance
    state: directory
    owner: "{{ perun_login }}"
    group: "{{ perun_group }}"
    mode: 0755

- name: Copy maintenance files
  template:
    src: "./maintenance/{{ item }}.j2"
    dest: "/var/www/maintenance/{{ item }}"
    owner: "{{ perun_login }}"
    group: "{{ perun_group }}"
    mode: 0644
  with_items: "{{ maintenance_files }}"

- name: Add EGI IGTF repository key
  apt_key:
    id: 3CDBBC71
    url: "https://dist.eugridpma.info/distribution/igtf/current/GPG-KEY-EUGridPMA-RPM-3"
    state: present
  when: apache_ca_certificate_path == "/etc/grid-security/certificates/"

- name: Add EGI IGTF repository
  apt_repository:
    repo: 'deb http://repository.egi.eu/sw/production/cas/1/current egi-igtf core'
    filename: 'igtf'
    state: present
  when: apache_ca_certificate_path == "/etc/grid-security/certificates/"

- name: Install latest IGTF certificates
  apt:
    name: ca-policy-egi-core
    state: latest
    update_cache: yes
  when: apache_ca_certificate_path == "/etc/grid-security/certificates/"
  notify:
    - "restart webserver"

# Rehash certificates for user identification
- name: Use c_rehash to your certificates
  command: c_rehash .
  args:
    chdir: "{{ apache_ca_certificate_path }}"
  when: apache_ca_certificate_path != "/etc/grid-security/certificates/"
  notify:
    - "restart webserver"

- name: Enable JSON data comprimation in Apache
  lineinfile:
    dest: /etc/apache2/mods-available/deflate.conf
    insertafter: "<IfModule mod_filter.c>\n"
    line: "\t\t# Perun\n\t\tAddOutputFilterByType DEFLATE text/javascript"
    regexp: "\t\t# Perun\n\t\tAddOutputFilterByType DEFLATE text/javascript"
    backrefs: yes
  notify:
    - "restart webserver"

