---

- name: Install sudo
  apt:
    name: sudo
    state: latest

- name: Install libpam-yubico
  apt:
    name: libpam-yubico
    state: latest

- name: create /etc/yubico
  file:
    path: /etc/yubico
    state: directory

- name: create /etc/yubico/authorized_yubikeys
  copy:
    content: ""
    dest: /etc/yubico/authorized_yubikeys
    force: no

- name: put users into /etc/yubico/authorized_yubikeys
  lineinfile:
    path: /etc/yubico/authorized_yubikeys
    line: "{{item}}:{{yubikey_users[item].yubikey}}"
  with_items: "{{ create_yubikey_users }}"
  
- name: Add Yubikey to sudo
  lineinfile:
    path: "/etc/pam.d/sudo"
    insertafter: '#%PAM-1.0'
    line: "auth sufficient pam_yubico.so authfile=/etc/yubico/authorized_yubikeys id={{ yubikey_id }} key={{ yubikey_key }}"

- name: Set permissions on /etc/pam.d/sudo
  file:
    path: /etc/pam.d/sudo
    mode: 0600

- name: create users
  user:
    name: "{{ item }}"
    comment: "{{ yubikey_users[item].name }}"
    shell: /bin/bash
  with_items: "{{ create_yubikey_users }}"

- name: ensure groups
  group:
    name: "{{ item }}"
  with_items: "{{ create_yubikey_users }}"

- name: ensure users in groups
  user:
    name: "{{ item }}"
    group: "{{ item }}"
  with_items: "{{ create_yubikey_users }}"

- name: create .ssh dirs
  file:
    path: "/home/{{ item }}/.ssh"
    owner: "{{item}}"
    group: "{{item}}"
    state: directory
    mode: 0700
  with_items: "{{ create_yubikey_users }}"

- name: create .ssh/authorized_keys
  copy:
    dest: "/home/{{ item }}/.ssh/authorized_keys"
    owner: "{{ item }}"
    group: "{{ item }}"
    content: "{{ yubikey_users[item].sshkey }}"
  with_items: "{{ create_yubikey_users }}"

- name: Add users to group sudo
  user:
    name: "{{item}}"
    groups: sudo
    append: yes
  with_items: "{{sudo_root_users}}"

- name: "check /home/{{perun_login}} existence"
  stat: path=/home/{{perun_login}}
  register: home_perun

- name: "create /home/{{perun_login}}/.ssh directory"
  file:
    path: "/home/{{perun_login}}/.ssh"
    owner: "{{perun_login}}"
    group: "{{perun_group}}"
    state: directory
    mode: 0700
  when:  home_perun.stat.exists

- name: enable Jenkins access to perun account
  copy:
    content: |
       ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdvdjIeskcNga9V59c8ADMx0XyXwDCr2kbErjcm/wuXBdnrNun2clcPmAq+qsdiED3ajeJhgLflDG+WMa49NP6P80+maK10fL1gtjvp3C8Nbx4r4Objtn0QI6aKjGEcvDUMBCd+4yRtuOfmhVYu3zCr1CswQgSBbRL+PxZtApC1wIaZPkEuCMhZRUL9iNI7n9pbjmI7Ibi8lfBTEp5TeiR05049BQN5oGGP9MmxvuAK3QWfz7ISZg62xqngcvELX28fkTvGC11GMN82PwCy0gv+VvYgBUwrPW6d1mI7oid8UvWchHJQ4oleLHP1yfY413sXBYij5u3zZkg+hy/P88d jenkins@perun-build.cesnet.cz
    dest:  "/home/{{perun_login}}/.ssh/authorized_keys"
    owner: "{{perun_login}}"
    group: "{{perun_group}}"
    mode: 0644
  when:  home_perun.stat.exists

- name: Add to sudoers
  lineinfile:
    path: "/etc/sudoers"
    line: "{{item}} ALL=(root) /bin/su - {{perun_login}}"
  with_items: "{{sudo_perun_users}}"
