---

- name: Copy perun-rpc.war file into tomcat webapps folder
  copy:
    src: "{{ perun_folder }}/perun-rpc/target/perun-rpc.war"
    dest: "/var/lib/{{tomcatN}}/webapps/perun-rpc.war"
    remote_src: yes
    owner: "{{tomcat_owner}}"
    group: "{{tomcat_group}}"
    mode: 0644

- name: Delete /var/www/perun-web-gui
  file:
    path: "/var/www/perun-web-gui"
    state: absent

- name: Deploy GUI
  command: cp -r ./perun-web-gui /var/www/perun-web-gui
  args:
    chdir: "{{ perun_folder }}/perun-web-gui/target/"

- name: Change owner of /var/www/perun-web-gui directory and its content to user perun
  file:
    path: /var/www/perun-web-gui
    state: directory
    owner: "{{ perun_login }}"
    group: "{{ perun_login }}"
    recurse: yes

- name: Sets rights on /var/www/perun-web-gui directory
  file:
    path: /var/www/perun-web-gui
    state: directory
    mode: 0755

- name: Start Tomcat if its not running
  become: true
  service:
    state: started
    name: "{{tomcatN}}"
