---

- name: Copy perun-rpc.war file into tomcat webapps folder
  command: cp perun-rpc.war "/var/lib/tomcat8/webapps/perun-rpc.war"
  args:
    chdir: "{{ perun_folder }}/perun-rpc/target/"

- name: Change rights on perun-rpc.war file
  file:
    path: /var/lib/tomcat8/webapps/perun-rpc.war
    owner: tomcat8
    group: tomcat8
    mode: 0644

- name: Delete /var/www/perun-web-gui
  file:
    path: "/var/www/perun-web-gui"
    state: absent

- name: Deploy GUI
  command: cp -r ./perun-web-gui /var/www/perun-web-gui
  args:
    chdir: "{{ perun_folder }}/perun-web-gui/target/"

- name: Change owner of /var/www/perun-web-gui directory and its content to user perun
  file:
    path: /var/www/perun-web-gui
    state: directory
    owner: "{{ perun_login }}"
    group: "{{ perun_login }}"
    recurse: yes

- name: Sets rights on /var/www/perun-web-gui directory
  file:
    path: /var/www/perun-web-gui
    state: directory
    mode: 0755

- name: Start Tomcat if its not running
  become: true
  service:
    state: started
    name: tomcat8
