---
# Task file for perun role for Debian

- name: Install prerequisites
  package:
    name: "{{ prerequisites[ansible_distribution] }}"
    state: latest

- name: "Create {{ perun_group }} group"
  group:
    name: "{{ perun_group }}"
    system: yes
    
- name: "Create {{ perun_login }} user"
  user:
    name: "{{ perun_login }}"
    group: "{{ perun_group }}"
    comment: "{{ perun_name }}"
    shell: /bin/bash
    system: yes

- name: Clone git repository of perun sources to remote server
  become: yes
  become_user: "{{ perun_login }}"
  git:
    repo: https://github.com/CESNET/perun.git
    dest: "{{ perun_folder }}"
    version: production
    update: yes

- name: Clone git repository of perun services to remote server
  become: yes
  become_user: "{{ perun_login }}"
  git:
    repo: https://github.com/CESNET/perun-services.git
    dest: "{{ perun_services_folder }}"
    version: production
    update: yes

