---
# do "apt-get update" if not run in the last 15 minutes (Oracle repository already existed)
- name: apt-get update 
  apt:
    update_cache: yes
    cache_valid_time: 900

- name: Install Java11
  apt:
    name: 
      - openjdk-11-jdk
    state: latest

- name: Install Maven 
  apt:
    name: maven
    state: latest

...
