---
# Task file for perun role for Debian distribution

# - name: Update apt-get
#   apt:
#     update_cache: yes

- name: Install prerequisites
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ prerequisites[ansible_os_family]}}"

- name: "Create {{ perun_login }} user"
  user:
    name: "{{ perun_login }}"
    comment: "{{ perun_name }}"
    #password: "{{ password_user_sha512 }}"
    password: "{{ password_user_sha512 | default (lookup('password'))}}"
    update_password: always

- name: "Add {{ perun_login }} user to sudoers"
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%{{ perun_login }}"
    line: "%{{ perun_login }} ALL=(ALL:ALL) ALL"

- name: Clone git repository of perun sources to remote server
  become: yes
  become_user: "{{ perun_login }}"
  git:
    repo: https://github.com/CESNET/perun.git
    dest: "{{ perun_folder }}"
    version: production
    update: yes

- name: Clone git repository of perun services to remote server
  become: yes
  become_user: "{{ perun_login }}"
  git:
    repo: https://github.com/CESNET/perun-services.git
    dest: "{{ perun_services_folder }}"
    version: production
    update: yes
