---
- name: Require Debian 9
  assert:
    that:
      - ansible_distribution == "Debian" 
      - ansible_distribution_major_version == "9" 
    msg: "Debian 9 specific tasks"

# do "apt-get update" if not run in the last 15 minutes (Oracle repository already existed)
- name: apt-get update 
  apt:
    update_cache: yes
    cache_valid_time: 900

- name: Install Java8
  apt:
    name: 
      - openjdk-8-jdk
    state: latest

- name: Install Maven 
  apt:
    name: maven
    state: latest

- name: Install tomcat8
  apt:
    name:
      - tomcat8
      - tomcat8-admin
      - tomcat8-user
      - libservlet3.1-java
    state: latest

- name: Install Shibboleth
  apt:
    name: libapache2-mod-shib2
    state: latest

...
