---
# Task file installing Shibboleth from SWITCH repo

- name: SWITCH repo key
  apt_key:
    id: 15B76742
    url: "http://pkg.switch.ch/switchaai/SWITCHaai-swdistrib.asc"
    state: present

- name: SWITCH repo
  apt_repository:
    repo: "deb http://pkg.switch.ch/switchaai/debian {{ ansible_distribution_release }} main"
    state: present
    filename: 'switch'
    update_cache: yes

- name: Install Shibboleth
  apt:
    name: shibboleth
    state: latest
    install_recommends: yes

- name: Generate Shibboleth key and cert
  command: shib-keygen
  args:
    chdir: /etc/shibboleth
    creates: /etc/shibboleth/sp-key.pem

- name: python-lxml
  apt:
    name: python-lxml

- name: shibboleth2.xml add attribute prefix AJP_
  xml:
    path: /etc/shibboleth/shibboleth2.xml
    xpath: /conf:SPConfig/conf:ApplicationDefaults
    namespaces:
      conf: urn:mace:shibboleth:2.0:native:sp:config
    attribute: attributePrefix
    value: "AJP_"

- name: shibboleth2.xml add epuid to REMOTE_USER
  xml:
    path: /etc/shibboleth/shibboleth2.xml
    xpath: /conf:SPConfig/conf:ApplicationDefaults
    namespaces:
      conf: urn:mace:shibboleth:2.0:native:sp:config
    attribute: REMOTE_USER
    value: "epuid eppn persistent-id targeted-id"

- name: shibboleth2.xml set handlerSSL="true"
  xml:
    path: /etc/shibboleth/shibboleth2.xml
    xpath: /conf:SPConfig/conf:ApplicationDefaults/conf:Sessions
    namespaces:
      conf: urn:mace:shibboleth:2.0:native:sp:config
    attribute: handlerSSL
    value: "true"

- name: shibboleth2.xml set cookieProps="https"
  xml:
    path: /etc/shibboleth/shibboleth2.xml
    xpath: /conf:SPConfig/conf:ApplicationDefaults/conf:Sessions
    namespaces:
      conf: urn:mace:shibboleth:2.0:native:sp:config
    attribute: cookieProps
    value: "https"
...
