---
# Task file for tomcat installation on Debian distribution

- name: Install tomcat7 packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ tomcat7_packages[ansible_os_family ]}}"

- name: Add user tomcat7 to group perun
  user:
    name: tomcat7
    groups: perun
    append: yes

- name: Disable autostart of system-wide tomcat when machine is rebooted
  service:
    enabled: no
    name: tomcat7

- name: Copy tomcat-users.xml and server.xml to tomcat 
  template:
    src: "{{ item }}.j2"
    dest: "/etc/tomcat7/{{ item }}"
    mode: 0640
    group: tomcat7
  with_items:
    - server.xml
    - tomcat-users.xml

- name: Export temporary password file for tomcat certificate to remote computer
  template:
    src: input.j2
    dest: "/home/{{ perun_login }}/input.txt"
    owner: "{{ perun_login }}"
    group: "{{ perun_group }}"
    mode: 0644

- name: Export certificate of machine (Apache) into format .p12
  command: openssl pkcs12 -passout "file:/home/{{ perun_login }}/input.txt" -export -out "{{ apache_p12_file }}" -in "{{ apache_certificate_file }}" -inkey "{{ apache_certificate_key_file }}"

- name: Delete temporary password file for tomcat certificate
  file:
    path: "/home/{{ perun_login }}/input.txt"
    state: absent

- name: Copy tomcat7 configuration to remote
  template:
    src: tomcat7.j2
    dest: "/etc/default/tomcat7"
    mode: 0644

- name: Restart Tomcat
  service:
    state: restarted
    name: tomcat7
