---
# Task file for tomcat installation on Debian distribution

- name: Install tomcat
  apt:
    name:
    - "{{tomcatN}}"
    - "{{tomcatN}}-admin"
    state: latest

- name: "Add user {{tomcat_owner}} to groups perun,{{tomcat_group}}"
  user:
    name: "{{tomcat_owner}}"
    groups: "{{ perun_group }},{{tomcat_group}}"
    append: yes

- name: "Add user {{ perun_login }} to group {{tomcat_group}}"
  user:
    name: "{{ perun_login }}"
    groups: "{{tomcat_group}}"
    append: yes

- name: Copy tomcat-users.xml and server.xml to tomcat
  template:
    src: "{{tomcatN}}/{{ item }}.j2"
    dest: "/etc/{{tomcatN}}/{{ item }}"
    mode: 0640
    group: "{{tomcat_group}}"
  with_items:
    - server.xml
    - tomcat-users.xml

## used only at the CESNET instance for http client
#- name: Export temporary password file for tomcat certificate to remote computer
#  copy:
#    content: |
#      {{password_tomcat_certificate}}
#    dest: "/home/{{ perun_login }}/input.txt"
#    owner: "{{ perun_login }}"
#    group: "{{ perun_group }}"
#    mode: 0640
#
#- name: Export certificate of machine (Apache) into format .p12
#  command: openssl pkcs12 -passout "file:/home/{{ perun_login }}/input.txt" -export -out "{{ apache_p12_file }}" -in "{{ apache_certificate_file }}" -inkey "{{ apache_certificate_key_file }}"
#
#- name: Make p12 file readable by tomcat
#  file:
#    path: "{{ apache_p12_file }}"
#    state: file
#    group: "{{tomcat_group}}"
#    mode: 0640
#
#- name: Delete temporary password file for tomcat certificate
#  file:
#    path: "/home/{{ perun_login }}/input.txt"
#    state: absent

- name: Create tomcat configuration file
  template:
    src: "{{tomcatN}}/{{tomcatN}}.j2"
    dest: "/etc/default/{{tomcatN}}"
    mode: 0644

- name: Create dirs to stop tomcat complaining
  file:
    path: "{{item}}"
    state: directory
  with_items:
     - "/var/lib/{{tomcatN}}/common/classes"
     - "/var/lib/{{tomcatN}}/server/classes"
     - "/var/lib/{{tomcatN}}/shared/classes"
     - "/usr/share/{{tomcatN}}/common/classes"
     - "/usr/share/{{tomcatN}}/server/classes"
     - "/usr/share/{{tomcatN}}/shared/classes"


- name: Restart Tomcat
  service:
    state: restarted
    name: "{{tomcatN}}"
