---
- name: create tomcat systemd service override dir
  file:
    path: "/etc/systemd/system/{{tomcatN}}.service.d"
    state: directory
- name: set system tomcat service
  copy:
    dest: "/etc/systemd/system/{{tomcatN}}.service.d/override.conf"
    content: |
      [Service]
      User={{tomcat_owner}}
      Group={{perun_group}}
  register: tomcat_override
- name: reload systemd
  systemd:
    daemon_reload: yes
    name: "{{tomcatN}}"
    state: restarted
  when: tomcat_override.changed
