---
# Tasks file for tomcat-perun
- include_tasks: "{{ ansible_os_family }}.yml"

- include_tasks: "Debian_10.yml"
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "buster/sid"
