---
# Tasks file for tomcat-perun
- include: "{{ ansible_os_family }}.yml"

- name: Create an instance of Tomcat in home as user perun
  become: yes
  become_user: "{{ perun_login }}"
  command: tomcat7-instance-create -p 8080 -c 8005 "/home/{{ perun_login }}/tomcat"
  args:    
    creates: "/home/{{ perun_login }}/tomcat/webapps/"

- name: Disable autostart of system-wide tomcat when machine is rebooted
  service: 
    name: tomcat7
    enabled: no
    state: stopped

# Ansible copy module cannot be used because both directories are on the remote side.
- name: Copy application tomcat-admin for easier remote deployment
  command: cp -r /usr/share/tomcat7-admin/manager/ "/home/{{ perun_login }}/tomcat/webapps/"

- name: Add records to tomcat-users.xml
  blockinfile:
    dest: /home/{{ perun_login }}/tomcat/conf/tomcat-users.xml
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    insertbefore: "^</tomcat-users>"
    block: |
        <role rolename="manager-gui"/>
        <role rolename="manager-script"/>
        <role rolename="standard"/>
        <user username="admin" password="{{ password_tomcat_admin }}" roles="standard,manager-gui,manager-script"/>

- name: Set connectors in server.xml
  blockinfile:
    dest: /home/{{ perun_login }}/tomcat/conf/server.xml
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    insertbefore: "<Engine name=\"Catalina\" defaultHost=\"localhost\">"
    block: |
        <Connector port="18443" protocol="HTTP/1.1" SSLEnabled="true" 
           maxThreads="150" scheme="https" secure="true" 
           clientAuth="false" sslProtocol="TLS" 

           keystoreFile="/etc/ssl/p12/ssl-cert-snakeoil.p12" 
           keystorePass="{{ password_certificate }}" keystoreType="PKCS12" 

        />

        <Connector port="8009" protocol="AJP/1.3" redirectPort="18443" address="127.0.0.1" tomcatAuthentication="false" URIEncoding="UTF-8"/>

#- name: Export certificate of machine (Apache) into format .p12
#  expect:
#    command: openssl pkcs12 -export -out "/etc/ssl/p12/ssl-cert-snakeoil.p12" -in "{{ SSLCertificateFile }}" -inkey "{{ SSLCertificateKeyFile }}"
#    responses:
#      password: "{{ password_certificate }}" 

#- name: Import certificates of server to the truststore -- THIS WILL DO ADMIN OF SERVER AFTER THE INSTALLATION OF PERUN BY HIMSELF!
#  command: keytool -keystore "~/.truststore" -importcert -trustcacerts -file "your_certificate" -alias "[cert alias, e.g. rt4.cesnet.cz]"

#- name: Set into start-up script of tomcat JAVA_OPTS with reference to .truststore -- I THINK THIS SHOULD BE DONE BY ADMIN OF SERVER TOO
#  command: JAVA_OPTS="-XX:MaxPermSize=512m -Xmx512m -XX:+UseConcMarkSweepGC -d64 -Dfile.encoding=UTF8 -Djavax.net.ssl.trustStore=/home/{{ perun_login }}/.truststore -Djavax.net.ssl.trustStorePassword={{ password_truststore }} -Djavax.net.ssl.trustStoreType=JKS"
