galaxy_info:
  author: Jan Zvěřina, Bruce Becker
  description: Configures the Tomcat
  company: CESNET, CSIR Meraka

  license: BSD

  min_ansible_version: 2.2

  platforms:
  
  - name: Debian
    versions:
    - stretch
    - jessie

  galaxy_tags:
    - web
    - identity

dependencies: []
